linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    # TODO: Add linter back when support for generics is available.
    #  ref: https://github.com/golangci/golangci-lint/issues/2649
    - typecheck
    # TODO: Add linter back when support for generics is available.
    #  ref: https://github.com/golangci/golangci-lint/issues/2649
    - unconvert
    # TODO: Add linter back when support for generics is available.
    #  ref: https://github.com/golangci/golangci-lint/issues/2649
    - unparam
    - unused
    # TODO: Add linter back when support for generics is available.
    #  ref: https://github.com/golangci/golangci-lint/issues/2649
    - whitespace

#run:
#  go: "1.22"
#  timeout: 10m
linters-settings:
  goconst:
    ignore-tests: true
#  golint:
#    min-confidence: 0
#  lll:
#    line-length: 160
#  gocritic:
#    # Note that the following checks are the default checks,
#    # plus builtinShadow. They are ordered as they appear on
#    # the explanation page, grouped by the type of check.
#    # Ref: https://go-critic.github.io/overview.html
#    enabled-checks:
#      # Diagnostic checks
#      - appendAssign
#      - caseOrder
#      - dupArg
#      - dupBranchBody
#      - dupCase
#      - dupSubExpr
#      - flagDeref
#      # Style checks
#      - assignOp
#      - builtinShadow
#      - captLocal
#      - defaultCaseOrder
#      - elseif
#      - ifElseChain
#      - regexpMust
#      - singleCaseSwitch
#      - sloppyLen
#      - switchTrue
#      - typeSwitchVar
#      - underef
#      - unlambda
#      - unslice
#  govet:
#    # report about shadowed variables
#    check-shadowing: true
#
#
#issues:
#  exclude-use-default: false
#  exclude-rules:
#    - path: pkg/di/doc.go
#      linters:
#        - gofmt
#        - goimports
#    - path: pkg/memoize/doc.go
#      linters:
#        - gofmt
#        - goimports
#    - path: pkg/maybe/doc.go
#      linters:
#        - gofmt
#        - goimports
#    - path: pkg/result/doc.go
#      linters:
#        - gofmt
#        - goimports
#    - text: "and that stutters"
#      linters:
#        - golint
#    - text: "error strings should not be capitalized or end with punctuation or a newline"
#      linters:
#        - golint
#    - text: "G101: Potential hardcoded credentials"
#      linters:
#        - gosec
#    - text: "should omit comparison to bool constant"
#      linters:
#        - gosimple
#    - text: "S1023: redundant `return` statement"
#      linters:
#        - gosimple
#    - text: "S1000: should use for range instead of for { select {} }"
#      linters:
#        - gosimple
#    - text: "ST1005: error strings should not be capitalized"
#      linters:
#        - stylecheck
#    - text: "should have a package comment, unless it's in another file for this package"
#      linters:
#        - golint
#    - text: "S1002: should omit comparison to bool constant"
#      linters:
#        - gosimple
#